### ISSUE TITLE
AudioSetting Unknown Struct

### ISSUE THREAD

**Issue by DanyaalMajid** [Adriwin06/Ultimate-CommonUI-Menu-System#15]
**Describe the bug**
The log shows the below message when packaging or cooking, and even in general engine startup logs:
LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /Game/CommonUI/Foundation/Save/BP_OptionsSaveGame.BP_OptionsSaveGame_C:AllAudioSettings'. Unknown structure.

**To Reproduce**
Build or Cook the project, it will fail only because of this.
Using City Sample 5.3.2 with Unreal Engine 5.3.2

**Comment by Adriwin06** [comment]
oh it's a common issue I got a lot of time working with structures. To fix it, 
1) change a value in the Struct_AudioSettings, then you can change the value again to what is was before
2) compile and save all blueprint that where using this structure (you can view them all by opening this structure, then you click on Asset at the top->reference viewer) 
3) it's now working

![image](https://github.com/Adriwin06/Ultimate-CommonUI-Menu-System/assets/76881633/c1fb3967-51de-4e93-bdaf-3c971bca19b2)

![image](https://github.com/Adriwin06/Ultimate-CommonUI-Menu-System/assets/76881633/236b8ff2-7cd4-4723-bb41-762755ed670c)

**Comment by DanyaalMajid** [comment]
Thanks for the solution, I also found an alternative solution which also works for me.

Open the affected struct, then refresh all nodes, and open the audio menu widget and refresh it's nodes as well, or simply use the Refresh All Nodes Plugin, save the project and build it, it should work now.
