### ISSUE TITLE
(MainMenu) Use camera instance rotation when moving

### ISSUE THREAD

**Issue by achillebourgault** [Adriwin06/Ultimate-CommonUI-Menu-System#19]
We can edit the blueprint **BP_FrontEndMenuCamera** to use the camera's current rotation when moving, instead of setting it to 0, 0, 0.
This enhancement will allow the camera to maintain its intended orientation during transitions, improving the overall user experience.

![UCMS_FrontEndMenuCamera](https://github.com/user-attachments/assets/178491b9-8075-4617-88e7-55252d1e9766)

**Comment by Adriwin06** [comment]
Hi! Thanks for the suggestion, it is a simple but good idea; I don't know why I never thought of it before 😅
You can make a pull request if you want, since it's your idea it's better if you add it yourself to keep the credits 😊
